
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/RandomHelper.ipynb

import random
import numpy as np

def rand_uniform_strong(min, max):
    if min > max:
        min, max = max, min
    return random.random() * (max - min) + min

def rand_scale(s):
    scale = rand_uniform_strong(1, s)
    if random.randint(0, 1) % 2:
        return scale
    return 1. / scale
